### ISSUE TITLE
Create PR for better review?

### ISSUE THREAD

**Issue by rolfschr** [ngi-nix/thunderbird-extensions#1]
Hi @eadwu,

I'd like to review your code and would rather use the GitHub PR feature. Could you create a branch with your changes, push it and create a PR? Something like

```
# Untested
$ cd /path/to/thunderbird-extensions
$ git checkout master # paranoia
$ git checkout -b thunderbird-extensions # keep track of current state
$ git push origin thunderbird-extensions && git branch --set-upstream-to=origin/thunderbird-extensions
$ git checkout master
$ git reset --hard ede0e0d # reset last commit from Eelco
$ git push -f origin master # erase in origin

# Open GitHub and create PR from branch thunderbird-extensions into master
```
This should allow me to easily comment on your code. What do you think?

**Comment by eadwu** [comment]
Like #2?

**Comment by rolfschr** [comment]
Perfect! I after opening the issue, I thought it would be better to keep ``master`` as is - I see you had the idea :+1:
